import { StyleSheet } from "react-native";
import { DefaultTheme, Fonts, Metrics, Colors } from "../../theme";

const { colors } = DefaultTheme;

export default StyleSheet.create({
  textTitle: {
    ...Fonts.Semibold(16),
    color: Colors.valhalla,
    marginTop: Metrics.heightRatio(21),
    marginBottom: Metrics.heightRatio(27.5),
    lineHeight: 19,
  },
  mainContainer: {
    flex: 1,
    alignItems: "center",
  },
  submainContainer: {
    alignItems: "center",
  },
  textPage: {
    ...Fonts.Semibold(14),
    color: Colors.valhalla,
    marginTop: Metrics.heightRatio(19.5),
    lineHeight: 17,
  },
  SubContainer: {
    marginHorizontal: Metrics.widthRatio(14),
    marginVertical: Metrics.heightRatio(20),
    paddingHorizontal: Metrics.widthRatio(18),
    borderRadius: 6,
    backgroundColor: Colors.white,
    width: "90%",
  },
  FragmentContainer: {
    width: "100%",
  },
  textQuestion: {
    ...Fonts.Semibold(16),
    color: Colors.valhalla,
    marginTop: Metrics.heightRatio(51),
    alignSelf: "flex-start",
    lineHeight: 26,
  },
  optionsContainer: {
    marginTop: Metrics.heightRatio(41),
  },
  selectedlistItem: {
    flexDirection: "row",
    width: "100%",
    paddingHorizontal: 10,
    paddingVertical: 13,
    borderWidth: 1,
    borderColor: Colors.lightGreen,
    borderRadius: 6,
    backgroundColor: Colors.lightGreen,
    marginTop: Metrics.heightRatio(10),
  },
  listItem: {
    flexDirection: "row",
    width: "100%",
    paddingHorizontal: 10,
    paddingVertical: 13,
    borderWidth: 1,
    borderColor: Colors.eastBay,
    backgroundColor: Colors.white,
    borderRadius: 6,
    marginTop: Metrics.heightRatio(10),
  },
  leftText: {
    ...Fonts.Regular(12),
    color: Colors.eastBay,
    alignSelf: "flex-start",
    lineHeight: 14,
    marginRight: 10,
  },
  leftSelectedText: {
    ...Fonts.Regular(12),
    color: Colors.white,
    alignSelf: "flex-start",
    lineHeight: 14,
    marginRight: 10,
  },
  leftAnsText: {
    ...Fonts.Regular(12),
    color: Colors.eastBay,
    alignSelf: "flex-start",
    lineHeight: 14,
    width: "80%",
    marginRight: 10,
  },
  leftSelectedAnsText: {
    ...Fonts.Regular(12),
    color: Colors.white,
    alignSelf: "flex-start",
    lineHeight: 14,
    width: "80%",
    marginRight: 10,
  },
  btnNext: {
    height: 40,
    width: Metrics.widthRatio(148),
    marginTop: Metrics.heightRatio(24),
    marginBottom: Metrics.heightRatio(31),
    backgroundColor: Colors.lightGreen,
    borderRadius: Metrics.heightRatio(6),
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  textNext: {
    ...Fonts.Semibold(14),
    color: Colors.white,
  },
  imgCongrats: {
    width: 70,
    height: 70,
    marginTop: Metrics.heightRatio(31),
    alignSelf: "center",
  },
  textCongrats: {
    ...Fonts.Semibold(24),
    color: Colors.lightGreen,
    alignSelf: "center",
    lineHeight: 34,
    marginTop: Metrics.heightRatio(24),
  },
  textFailed: {
    ...Fonts.Semibold(24),
    color: Colors.red,
    alignSelf: "center",
    lineHeight: 34,
    marginTop: Metrics.heightRatio(24),
  },
  textPassed: {
    ...Fonts.Regular(13),
    color: Colors.valhalla,
    alignSelf: "center",
    lineHeight: 23,
    marginTop: Metrics.heightRatio(13),
  },
  imgCertificate: {
    width: Metrics.widthRatio(210),
    height: Metrics.heightRatio(142),
    marginTop: Metrics.heightRatio(10),
    alignSelf: "center",
  },
  textItemTitle: {
    ...Fonts.Semibold(14),
    lineHeight: 16,
    marginTop: Metrics.heightRatio(24),
    color: Colors.valhalla,
    textAlign: "center",
  },

  textItemDesc: {
    ...Fonts.Regular(12),
    lineHeight: 18,
    marginTop: Metrics.heightRatio(20),
    color: Colors.paleGray,
    textAlign: "center",
    marginHorizontal: Metrics.widthRatio(22),
  },
  activityIndicator: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    height: 80,
  },
});
