//
//  String.js:
//  BoilerPlate
//
//  Created by Retrocube on 10/4/2019, 9:49:09 AM.
//  Copyright © 2019 Retrocube. All rights reserved.
//
const PLACEHOLDER = {
  full_name: "Full Name",
  email: "Email Address",
  dob: "Select Date",
  password: "Password",
  firstName: "First Name",
  lastName: "Last Name",
  username: "Username",
  gender: "Gender",
  phoneNumber: "Phone Number",
  address: "Address",
  confirmPassword: "Confirm Password",
  groupName: "Name your group",
  status: "Status",
  occupation: "Artist",
  haircolor: "Blonde",
  eyecolor: "Hazel Brown",
  search: "Search",
  selectCategory: "Select Category",
  description: "Description",
  message: "Type your message here",
  Name: "Name",
  emailAddress: "Email Address",
  not_aval: "Not Available",
};
const TITLES = {
  screenLogin: "Login",
  home: "Home",
  myTrainings: "My Trainings",
  news: "News",
  faqs: "Help, FAQs",
  privacyPolicy: "Privacy Policy",
  termsConditions: "Terms & Conditions",
  support_chat: "Support Chat",
  My_Certificates: "My Certificates",
  quiz: "Quiz",
  Courses: "Courses",
  CourseDetails: "Course Details",
  Language: "Language",
  Certificate: "Certificate",
  Notification_Settings: "Notification Settings",
  Change_Password: "Change Password",
  EditProfile: "Edit Profile",
  bottomTitleLogin: "By signing up, you agree with our",
  accountTitle: "Already have an Account?",
  profile: "Profile",
  setup_account: "Setup Account",
  setup_01: "Step 01",
  setup_02: "Step 02",
  people_who_reacted: "People who reacted",
};
const LABEL = {
  Sign_in_to_your_Account: "Sign in to your account",
  Forgot_Password: "Forgot your password?",
  Select_Language: "Select Language",
  seeAll: "View all",
  viewMore: "view more",
  readMore: "read more",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm Password",
  sign_with: "- Or sign in with -",
  loginBtn: "Sign in",
  register: "Register",
  submit: "Submit",
  start_quiz: "START QUIZ",
  continue: "Continue",
  forgotPassword: "Forgot password?",
  Edit_Profile: "Edit Profile",
  txtEnteryourEmail:
    "Enter your email below and we will send you a reset email.",
  sign_google: "Sign In with Google",
  sign_facebook: "Sign In with Facebook",
  sign_apple: "Sign In with Apple",
  dont_account: "Don't have an account?",
  full_name: "Full Name",
  phoneNumber: "Phone Number",
  signUp: "Sign up",
  already_account: "Already have an account?",
  signIn: "Sign in",
  dob: "Date of Birth",
  occupation: "Occupation",
  haircolor: "Hair Color",
  eyecolor: "Eye Color",
  forgot_password: "Forgot Password",
  save: "Save",
  send: "Send",
  update: "Update",
  edit: "Edit",
  delete: "Delete",
  done: "DONE",
  next: "NEXT",
  return_to_home: "RETURN TO HOME",
  no: "No",
  yes: "Yes",
  post: "POST",
  termsConditions: "Terms & Conditions",
  createGroup: "Create Group",
  invite: "Invite",
  invited: "Invited",
  Interest_and_Hobbies: "Interest & Hobbies",
  select_gender: "Select Gender",
  male: "Male",
  female: "Female",
  My_Certificates: "My Certificates",
  Help: "Help,FAQ",
  privacyPolicy: "Privacy Policy",
  Language: "Language",
  Change_Password: "Change Password",
  Notification_Settings: "Notification Settings",
  Logout: "Logout",
  viewCertificate: " VIEW CERTIFICATE",
  Current_Password: "Current Password",
  New_Password: "New Password",
  Confirm_New_password: "Confirm New Password",
  Name: "Name",
  emailAddress: "Email Address",
};

const ERROR = {
  please_enter_valid_email: "Please enter valid email",
  please_enter_valid_password: "Please enter valid password",
  please_enter_full_name: "Please enter your full name",
  please_enter_name: "Please enter your name",
  please_enter_phone_number: "Please enter phone number",
  please_select_date_of_birth: "Please select date of birth",
  please_enter_occupation: "Please enter occupation",
  please_select_hair_color: "Please select hair color",
  please_select_eye_color: "Please select eye color",
  please_select_at_least: "Please select at least 1 item",
  please_upload_at_least: "Please upload at least 1 photo or video",
  please_enter_valid_number: "Please enter valid number",
  please_select_at_least_ans: "Please select at least 1 answer",
};

export default {
  PLACEHOLDER,
  LABEL,
  TITLES,
  ERROR,
};
